# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
xcodeproj 'IP Locator'
target 'IP Locator' do
	pod 'Alamofire', '~> 1.2.1'
end

target 'IP LocatorTests' do

end

