# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
xcodeproj 'IP Locator'
target 'IP Locator' do
	pod 'Alamofire', '~> 3.0'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
end

target 'IP LocatorTests' do

end

